export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const GET_PROFILE_BY_ID_START = 'GET_PROFILE_BY_ID_START';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';
export const GET_PROFILE_BY_ID_FAIL = 'GET_PROFILE_BY_ID_FAIL';

export const GET_ALL_PROFILES_START = 'GET_ALL_PROFILES_START';
export const GET_ALL_PROFILES_SUCCESS = 'GET_ALL_PROFILES_SUCCESS';
export const GET_ALL_PROFILES_FAIL = 'GET_ALL_PROFILES_FAIL';

export const GET_GITHUB_REPOS_START = 'GET_GITHUB_REPOS_START';
export const GET_GITHUB_REPOS_SUCCESS = 'GET_GITHUB_REPOS_SUCCESS';
export const GET_GITHUB_REPOS_FAIL = 'GET_GITHUB_REPOS_FAIL';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const ADD_EXPERIENCE_START = 'ADD_EXPERIENCE_START';
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL';

export const ADD_EDUCATION_START = 'ADD_EDUCATION_START';
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
export const ADD_EDUCATION_FAIL = 'ADD_EDUCATION_FAIL';

export const DELETE_EXPERIENCE_START = 'DELETE_EXPERIENCE_START';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';

export const DELETE_EDUCATION_START = 'DELETE_EDUCATION_START';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';
